# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Full_Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
    - name: Create expired_filter.keys.json
      env: 
        FIELD: ${{ secrets.EF_FIELD }}
        KEY: ${{ secrets.EF_KEY }}
        INDEX: ${{ secrets.EF_INDEX }}
      run: |
        mkdir keys
        echo {field: $FIELD, key: $KEY, index: $INDEX} > keys/expired_filter.keys.yml
    - name: Test Run 
      run: |
        python3 src/Expired_Filter/Expired_Filter.py -p 4 
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: ExpiredJobs.xlsx    